### ISSUE TITLE
Key-based reordering doesn't work

### ISSUE THREAD

**Issue by mindplay-dk** [132yse/fre#58]
I have started working on a [test](https://github.com/132yse/fre/commit/4cd9f44dbfdb57f67954ed44bb7547d241fb12ed) for key-based element reordering.

I suspected this wasn't working, so I decided to build a practical example:

https://codesandbox.io/s/fre-demo-uxuic

In this example, I have a list of counter IDs only (in `counters` in `App`) with the actual counter values being maintained in instances of `Counter`.

As you can see, I'm using a `key`-attribute on the `<Counter/>` instances, so the instances (with state) should be preserved between updates - which they are.

But the *order* of the component instance elements does not get updated.

Here's an image to explain:

![image](https://user-images.githubusercontent.com/103348/66271656-e0f27000-e860-11e9-8adc-e0d8757ba528.png)

As you can see in the console the "Remove" button handler has reversed the order of the counter IDs from `1, 2, 3` to `3, 2, 1`.

But as shown with the red lines, the order of the components in the DOM is still `1, 2, 3`, so the reordering doesn't seem to work.

**Comment by 132yse** [comment]
I saw the use cases and probably knew where was wrong.
We can continue testing other use cases.
Then I'll fix it as soon as possible until I get online.

**Comment by 132yse** [comment]
I've fixed this bug just now, and the tests was passed.😁

**Comment by mindplay-dk** [comment]
Doesn't look like it's fixed yet - try pressing the +/- buttons after pressing reverse in the demo?

This happens:

![image](https://user-images.githubusercontent.com/103348/66305995-ddaec100-e900-11e9-8c6e-a37cff2e6f8f.png)

**Comment by mindplay-dk** [comment]
The [test](https://github.com/132yse/fre/commit/4cd9f44dbfdb57f67954ed44bb7547d241fb12ed) I mentioned doesn't pass - but I'm not sure if the test is correct yet, it might not be.

**Comment by 132yse** [comment]
Now it looks like remove element has a problem. It's desperate.

**Comment by 132yse** [comment]
I fixed it again, but I tried to test the case and found it still failed.

**Comment by 132yse** [comment]
@mindplay-dk Wrong closure, I'm back again :sad:
Now I think I've fixed the problem, but still need testing. Thank you for your patience :thank:.

**Comment by mindplay-dk** [comment]
Sorry, but the demo still doesn't work.

Don't worry if it takes you some time to figure this out - getting this exactly right is probably *the* most difficult part of virtual DOM. It's not supposed to be easy 😉

**Comment by 132yse** [comment]
@mindplay-dk My demo here is working correctly. Are you sure you are the latest version(v1.7.7)?
Or what step is not working?

**Comment by mindplay-dk** [comment]
Try copy/pasting the ESM build into `fre.js` in this demo project:

https://codesandbox.io/s/fre-demo-uxuic

Currently, it doesn't sort the components when you press "Reverse".

(and for some reason CodeSandbox is crashing right now if I'm logged in, so I haven't been able to save this sandbox with a new version of the library...)

**Comment by 132yse** [comment]
My mistake, my use case, lost the key attribute, and the problem still exists.
It's really hard. I still need time...

**Comment by mindplay-dk** [comment]
No pressure, take your time 🙂

**Comment by 132yse** [comment]
I'm back again... I seem to have really fixed this now. Please check it 😭

**Comment by mindplay-dk** [comment]
I think you're getting closer - it works now as long as you don't press any of the +/- buttons... so, as long as you don't change the state, adding/removing and reordering the counters seems to work.

But as soon as you've pressed one of the +/- buttons, it breaks.

**Comment by 132yse** [comment]
I've fixed it again by again. Hope that this is the last time, my God.

**Comment by mindplay-dk** [comment]
[Looks solid](https://codesandbox.io/s/fre-demo-uxuic)! 😀🎉

So at this point, I would suggest, hold off making anymore changes to reconciliation, until we have the test in place - making changes at that point will be much safer.

I will try to finish the test soon.

**Comment by mindplay-dk** [comment]
Closing, since we have the tests for key-based reconciliation in place. 👍
